// ---------------- COMMENT POOL ----------------
const commentPool = [
  "you are the birthday 🎂",
  "this is giving main character energy",
  "big 'I understood the assignment' energy",
  "no thoughts, just vibes",
  "this is violently relatable",
  "I'm deceased 💀",
  "she ate and left no crumbs",
  "this is unhinged (in a good way)",
  "lowkey this is art",
  "rent-free in my head now",
  "this is a cultural reset",
  "this is chaos but make it aesthetic",
  "Iron rusts from disuse, stagnant water loses its purity and in cold weather becomes frozen; even so does inaction sap the vigor of the mind.",
  "Nothing is hidden beneath the sun.",
  "Obstacles cannot bend me. Every obstacle yields to effort.",
  "We make our life by the death of others.",
  "Necessity is the mistress and guardian of nature.",
  "One ought not to desire the impossible.",
  "He who neglects to punish evil sanctions the doing thereof.",
  "Darkness is the absence of light. Shadow is the diminution of light.",
  "He who does not value life does not deserve it.",
  "Simplicity is the ultimate sophistication.",
  "Nothing strengthens authority so much as silence.",
  "I fear this is too accurate.",
  "this unlocked a memory I didn't ask for",
  "live from my brain, it's absolute chaos",
  "this feels like a sketch that went off the rails",
  "why did I read this in a fake news voice",
  "this is giving 'Weekend Update energy'",
  "somebody get a producer in here",
  "I can hear the studio audience laughing already",
  "this should not have been this funny",
  "this is giving 'digital cold open' energy",
  "I feel like this needs a cue card",
  "this is one take away from disaster",
  "I know the writers were laughing while making this",
  "this belongs in a highlight reel",
  "this is giving 'we lost control of the sketch' energy",
  "someone please cut to commercial",
];
